# Generated by Django 6.0.2 on 2026-02-24 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treinos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exerciselog',
            old_name='duration_secods',
            new_name='duration_seconds',
        ),
    ]
